### ISSUE TITLE
Tensorflow custom env

### ISSUE THREAD

**Issue by robmarkcole** [aws/studio-lab-examples#46]
Request Tensorflow custom env example yml

**Comment by robmarkcole** [comment]
This recipe appears to work fine, although I haven't tested the GPU, or newer versions of tensorflow:

```yml
name: tensorflow
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - ipywidgets
  - conda
  - conda:
    - cudatoolkit=10.1
    - cudnn=7.6
    - nccl=2.4
    - pip=20.0
    - tensorflow-gpu=2.2
    - ipykernel
```
