### ISSUE TITLE
Example pytorch env

### ISSUE THREAD

**Issue by robmarkcole** [aws/studio-lab-examples#59]
As title, with GPU dependencies installed. Thanks

**Comment by robmarkcole** [comment]
The below recipe appears fine:

```yml
name: pytorch
dependencies:
  - python=3.9
  - pip
  - pip:
    - ipywidgets
  - conda
  - conda:
    - ipykernel
    - pytorch 
    - torchvision
```
